### ISSUE TITLE
Discussion for ARC-0001 - Algorand Wallet Transaction Signing API

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#1]
Draft is https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0001.md
See also proposed PR that may be listed below.

**Comment by DanBurton** [comment]
Nitpick: I suggest the function be referred to as `signTxns` rather than `signTxn`, since it accepts an array of transactions to sign.

**Comment by DanBurton** [comment]
> If txns[i].signers is an empty array, the transaction txns[i] MUST not be signed and ret[i] MUST be set to null.

I propose that transactions which are "not to be signed" may include a field `stxn` which may take the place of `null` in the result.

Proposed replacement to the above wording:

> If `txns[i].signers` is an empty array, the transaction `txns[i]` MUST not be signed and `ret[i]` MUST be set to `txns[i].stxn`, or `null` if the `stxn` field is not present on `txns[i]`.

**Comment by DanBurton** [comment]
For reference, my proposed changes regarding `txns[i].stxn` are influenced by [ARC-0010's additional requirements regarding LogicSigs](https://github.com/reach-sh/ARCs/blob/6fa84a13bec22baab6ced0d0fac10e2a3b1b8170/ARCs/arc-0010.md#additional-requirements-regarding-logicsigs) and writing [the source for DemoWallet.js](https://github.com/reach-sh/algo-demo-wallet/blob/2d1e5d79398ac2f21acab8362d074004c5390652/DemoWallet.js#L71-L73).

**Comment by fabrice102** [comment]
Thanks for the feedback @DanBurton . See #29 and #28
