### ISSUE TITLE
Discussion for ARC-0020: Smart ASAs

### ISSUE THREAD

**Issue by aldur** [algorandfoundation/ARCs#109]
This is the discussion for [ARC-0020](https://github.com/algorandfoundation/ARCs/pull/91).

**Comment by cusma** [comment]
Since the discussion has been open for 15 days already and there are no objections and / or observations, maybe we could consider merging it?

@fabrice102 @wheresaddie @aldur @jannotti

**Comment by aldur** [comment]
Agreed 👍
