### ISSUE TITLE
Creating ARC to be used by the swap tools providers

### ISSUE THREAD

**Issue by ipaleka** [algorandfoundation/ARCs#110]
Some of those providers like [Atomixwap](https://atomixwap.xyz/) provide a custom note, but others like [Swapper](https://app.swapper.tools/) don't.

A note standard used by the providers, with at least the provider's identifier and type of tool (*swap* or so), would be highly beneficial for the Algorand community.

**Comment by SudoWeezy** [comment]
Is [ARC-2](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0002.md) not enough for that?

**Comment by ipaleka** [comment]
> Is [ARC-2](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0002.md) not enough for that?

Yes, it can, now the only task remaining is to call on providers to actually fill their notes using the ARC-2. :)

Thank you!
