### ISSUE TITLE
Discussion: Extended Application Specification

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#118]
We should consider extending the current ARC4 contract description with additional data.

The additional data might include:

- State  keys/types 
- Data structures used 
- Hints or default parameters for methods.

**Comment by jannotti** [comment]
One reason people often ask for the state schema to be exposed is so that callers can know
 1. How much min balance is required to opt-in
 2. Whether opt-ins are required at all

But just because there's a local state schema, that doesn't mean that accounts must be opted-in for every possible invocation of the contract.  There may be some calls that don't require the user to be opted in. Imagine, for example, an AMM that offers price information from a call that only examines global state. So this might fall under the "Hints" mentioned in the main description - does this method require opt-in?

**Comment by barnjamin** [comment]
Good point, having methods marked with an `authorized: opted in` and conveying that info to the caller would be a good addition

**Comment by barnjamin** [comment]
See also prior art here: https://github.com/algorandfoundation/ARCs/pull/75

**Comment by cusma** [comment]
I'm not sure this is the right place to discuss it but: I was considering that with the introductions of op-code budget utilities such as [`OpUp` in PyTeal](https://pyteal.readthedocs.io/en/latest/opup.html), a client should be able to discover the cost of an ABI call that eventually triggers Inner Transactions with the purpose of increasing the op-code budget. Maybe this could be just mentioned in the method's descriptions if we think that a specific ABI JSON field is too much.

**Comment by jannotti** [comment]
I agree that info about cost is potentially useful, but I also worry that a) it might be dynamic, based on the input data, and b) even if static, it seems brittle to friend on it, if a contract you are calling is updateable. (That is, it might be reasonable to assume a contact won't change its method availability, but not changing its precise cost send like a big ask)

So we would need to figure out how to offer guidance without tripping on those issues.

**Comment by fabrice102** [comment]
Regarding contract update, I think metadata must be updated in that case.

**Comment by cusma** [comment]
I think it is definitely useful to include a structured standardisation of the state (`global` and `local`) in the ABI JSON. I saw there are some concerns about Boxes, which introduce a state that is not _know in advance_ at compiling/creation time. I think we should treat the state “statically allocated” (in the original form) differently from the state “dynamically allocated” through Boxes. I’m in favour of having the “static” one structured and standardised in the JSON ABI and the “dynamic” one somehow appended as JSON appendix with the Box itself. In this way we gain already a very useful standardisation that covers all those apps that not make use of Boxes and have an escape valve for the state appended dynamically later on with Boxes.

**Comment by jannotti** [comment]
I'm not sure the difference between status and dynamic is as straightforward as global/local vs boxes.

NFDs, for example, have user defined keys. A new "standard" among NFDs could emerge in which a particular key has a particular type, but that was not known at contract creation time.

Conversely, I expect some usage of boxes to be quite static. I was recently recommending to a project that they use one global box, maybe named "balances" or whatever, to hold a list of asset, balance pairs. They could statically declare the abi type of such a box.
