### ISSUE TITLE
DISCUSSION: TOKEN(NFT) BURN FEATURE WITHOUT REQUIRING CREATOR ADDRESS POST-TRANSFER

### ISSUE THREAD

**Issue by kcelestinomaria** [algorandfoundation/ARCs#120]
Hello Algorand Community and Algorand Foundation,

Tokens, such as NFTs, require that the Creator Address be provided if the NFT or FT is being burnt. This is very limiting. We have a use-case where we want users to buy utility NFTs and then use them within a specific timeframe to unlock rewards. The creator of these NFTs is an Admin Address in a smart contract. However, since we intend to have a specific timeframe to enforce rarity and increase the value of the NFTs by inducing a sense of urgency(setting expiry), we need to be able to burn these NFTs if the buyer or bidder passes the timeframes without using them. However, this is impossible and very complex because we then have to get the address of the Admin everytime to burn an NFT or token for that matter yet at this point in time it is not with the Admin Address(was already bought, and transferred). Requesting for this feature to be enabled or a workaround that makes NFTs a breeze.

Thanks.

**Comment by kcelestinomaria** [comment]
Hello @fabrice102  @barnjamin , we are having this issue in our use-case where we are tokenizing physical assets, and then selling rights for these physical assets in an NFT Marketplace. These NFTs represent rights, and as such after being used they should get burnt, but every call to burn them requires the Creator Address be provided, hard to determine in a smart contract cause the creators are arbitrary

**Comment by kcelestinomaria** [comment]
This feature request could succeed the upcoming box storage feature to be approved as PR by @jannotti here: https://github.com/algorand/go-algorand/pull/4149

How it could be incorporated is that since we would be able to create maps with arbitrary keys or non-address key types, then we could key NFTs with something else like an external hash etc(any other that an application developer provides). and use that as a parameter to burn the NFT.

**Comment by SudoWeezy** [comment]
Hello @kcelestinomaria,
 
Could you please move this Idea to the forum? https://forum.algorand.org/c/arc/19
From now on, [issues](https://github.com/algorandfoundation/ARCs/issues) will be used only to talk about ARC already in the repository.

Thanks!

**Comment by kcelestinomaria** [comment]
These processes are too long to be honest, plus I doubt any feature proposals get implemented or discussed, only insider requests or those from the Algorand Team, always brought them on the forum but there was always more confusing explanations with explicit refusals to improve. So this won't work, been here before, really tired on trying to request improvements on Algorand that help power real-world use cases and benefits, it's sucking my blood now to be honest, will find workarounds using our own tech side. Thanks! @SudoWeezy
