### ISSUE TITLE
Discussion for ARC-0021 : Round based datafeed oracles on Algorand

### ISSUE THREAD

**Issue by SudoWeezy** [algorandfoundation/ARCs#124]
This is the discussion about the [ARC-21](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0021.md)

These conventions aim to make it easier for smart contracts to interact with off-chain data sources.

**Comment by jzjones** [comment]
@SudoWeezy Couple of minor things:
Is `[]byte` a valid ABI type? I have only seen it as `byte[]` in other places

For some data it may not have a value at every round, but there may be a desire to get the closest value to a specified round, or the most recent. Something like `get_closest` or `get_latest`. Both of these methods would probably need thresholds to allow some control over the span of rounds it will search on, i.e. get latest value no more than 5 rounds old, etc

**Comment by SudoWeezy** [comment]
Sorry for the time to reply. I did not get the notification when you posted it, @jzjones.
Tagging the author @ori-shem-tov

Is there a particular reason for the []byte naming?
from arc-4 `<type>[]: A variable-length array. type can be any other type.`

I like those `get_closest` / `get_latest` methods, what do you think ?

**Comment by SudoWeezy** [comment]
@jzjones Can you please make a PR to add these 2 functions to ARC-21 as "OPTIONAL"?
