### ISSUE TITLE
Discussion for ARC-36: propose to add a new top-level field to support custom UI filters

### ISSUE THREAD

**Issue by stein-f** [algorandfoundation/ARCs#163]
Creators often want to define filterable custom attributes that do not impact NFT ranking. If filterable attributes were defined in a standardised way frontends could provide filtering support on these attributes. Examples are "dream state" for mostly frens or filtering on animated traits only for FUMs.

This change is backwards compatible.

Example:

```json
{
  "properties": {
    "background": "yellow",
    "head": "curly"
  },
  "filters": {
    "dream stage": "REM"
  }
}
```

**Comment by TommyAlex79** [comment]
I like that this is "backward compatible" in the sense that before someone adds support, things will still work fine, just you would not get the new functionality,

**Comment by stitchmngo** [comment]
I like it. I can see a lot of use cases to having separate metadata without affecting rarity score

For example: 

- Storing XP credits + levelling systems
- Flag a stolen asset 
- Utility expiration tags: if the NFT was used as a token to claim another asset or enter a competition (eg MNGO dreaming mostly frens, or V1 Goannas that have been mutated/zombified) the field could be useful in marketplaces.
- SubDAOs/Groups - sub DAOs often form together but a trait isn't always enough to signal if an asset is active participant.

**Comment by stein-f** [comment]
It might also be desirable to support a wider category of filter types, such as a numeric range filter. In this case a more complex filter model would need to be defined. For example

```json
{
  "properties": {
    "background": "yellow",
    "head": "curly"
  },
  "filters": [
    {
      "type": "range",
      "name": "xp",
      "value": 120
    },
    {
      "type": "category",
      "name": "dream state",
      "value": "REM"
    }
  ]
}
```

**Comment by KillerGasy** [comment]
I am in support of this. I think this is a good idea, considering how vital rarity is.

**Comment by solkimicreb** [comment]
I love this. Can we add the same thing to arc3? It would be really cool if the two standards had a similar structure when possible.

Can someone create a PR for this? I think we would be all happy to upvote it to the moon.

**Comment by stein-f** [comment]
> I love this. Can we add the same thing to arc3? It would be really cool if the two standards had a similar structure when possible.
> 
> Can someone create a PR for this? I think we would be all happy to upvote it to the moon.

Yes I was thinking of also adding to arc3 once we agree on an approach for arc69. I can put together a PR.

**Comment by pbennett** [comment]
This really isn't about ARC69 but metadata in general.  ARC3 or for mutability, ARC19 both could contain these filters.
Filters could obviously mutate with ARC19 as well.

**Comment by SudoWeezy** [comment]
@stein-f, I agree with @pbennett, it's a metadata standards.
You can create PR for a new ARC based on [ARC-16](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0016.md).

**Comment by SudoWeezy** [comment]
PR for this -> https://github.com/algorandfoundation/ARCs/pull/176

**Comment by SudoWeezy** [comment]
ARC-36 -> Last call Status, https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0036.md

Please feel free to comment or add a new PR if needed.
