### ISSUE TITLE
Discussion: Removal of `tokenOfOwnerByIndex` from ARC-72 Enumeration Extension

### ISSUE THREAD

**Issue by AustP** [algorandfoundation/ARCs#172]
ARC-72 defines the enumeration extension which includes the `balanceOf`, `totalSupply`, `tokenByIndex`, and `tokenOfOwnerByIndex` methods. I propose removing `tokenOfOwnerByIndex` from the enumeration extension.

In order to support `tokenOfOwnerByIndex`, a dynamic list must be stored for each user. As the user acquires more NFTs, the list will grow longer and require multiple boxes to contain it. Transferring an NFT from User A to User B will require 3-5 boxes depending on how many NFTs both users own. The worst part is that the number of boxes (and their names) change based on the current state of the smart contract (i.e. how many NFTs each user owns). This state dependency makes it difficult to interact with the smart contract programmatically. The simulate endpoint could help determine which boxes to include, but because they are dynamic, there is still a chance of box mismatch between simulation and execution. There would also be troubles if someone was trying to transfer large amounts of NFTs via a script or something.

Although `tokenOfOwnerByIndex` makes it easy to get a list of NFTs owned by a specific user, you can still get that information without this method. Granted, it would require iterating over the whole collection and filtering the results, but the simulate endpoint will help with that. Also, I suspect that most people will get the information from an NFT indexer instead of the blockchain anyways.

Keeping `tokenOfOwnerByIndex` in the extension seems like more trouble than it's worth at the moment. If a contract emitted it but kept the other three methods, there's no easy way for the contract to convey that information because they don't support the whole interface. Keeping it in the spec adds so much complexity that I guess most people will choose not to include the entire extension which limits future tooling and adoption.

@willghatch @SudoWeezy

**Comment by SudoWeezy** [comment]
The arc still needs to be finalized, could you please create a PR to remove this part, and what you find is not convenient @willghatch? (Please let me edit access on the PR)
Also, there will be a Discord discussion to discuss this NFT standard Thursday 9th of March 2023:
 https://discord.com/events/491256308461207573/1080830179649261638

**Comment by AustP** [comment]
Closed by #173
