### ISSUE TITLE
Discussion: "Design Algorand for Everyone"

### ISSUE THREAD

**Issue by kcelestinomaria** [algorandfoundation/ARCs#174]
Hey, is it possible to have multi-language support for passphrases on Algorand? 

Bitcoin has a multi-language standard via BIP-0039 .

![image](https://user-images.githubusercontent.com/46893114/222595879-aa8369fa-bb7b-463f-a71b-2f07e53d913c.png)

I lead the team at JASIRI(https://jasiriprotocol.org) , and we have a wallet we are working to ensure remains very inclusive for all users on the network, we are onboarding users and most don't necessarily speak English or even simply do not prefer it. Our wallet has multi-language support, but the passphrase set-up part, it comes natively from the Algorand SDKs, yet the Algorand SDKs only support English, sadly.  

Could we put this as an ARC and have it considered?

Thanks and regards.

**Comment by SudoWeezy** [comment]
Hello, it's a really good idea. You can submit an ARC. 

Our wordlist is here: 
https://github.com/algorand/go-algorand/blob/master/crypto/passphrase/wordlist.go

Please take examples of what they have done on the BIP-39. 
https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by kcelestinomaria** [comment]
Hey @SudoWeezy , thanks a lot. Will add and take examples from BIP-39, though I need to ask, there are some languages that are not on BIP-39 , but would be a really good idea to have them supported for Algorand. We ran a testnet invitation for our project a couple of weeks back and uncovered ecosystem participation + interest from speakers/communities of these languages: **Arabic** and **Bahasa Indonesia** ... for us to support these languages we would need developers from these communities to add support, right? We could have the ARC be rolling for sometime, asking any developer who can add their language for support to contribute if they want to . Is this approvable for the ARC? Thanks.

**Comment by SudoWeezy** [comment]
Yes it's fine, as long as the process is approved.
From my point of view, PR could be submitted in the future to the assets/arc-00XX/ repository with other languages.

**Comment by kcelestinomaria** [comment]
Hey @SudoWeezy , do I do it 100% as is with BIP-39, should be a good place to start from, right?

**Comment by SudoWeezy** [comment]
Hey, after an internal discussion, we think it should be sufficient for the SDKs to follow the existing BIP-39.
Could you please raise the issue (your first post) here instead: https://github.com/algorand/go-algorand/issues.

Thanks!

**Comment by kcelestinomaria** [comment]
@SudoWeezy Just did what you asked, here it is: https://github.com/algorand/go-algorand/issues/5215 , thanks!
