### ISSUE TITLE
Discussion for ARC-0002 - Algorand Transaction Note Field Conventions

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#2]
Draft is https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0002.md
See also proposed PR that may be listed below.

**Comment by scholtz** [comment]
in the voting system and in the donation app i have came to conclusion that it is better to mark transaction for lookup with some lookup index.

eg if there is a question in the format

avote-question/v1:j{"t":"Hello world","q":"How do you like this voting system?","max":16024568,"category":"community","o":{"1":"I love it","2":"I like it","3":"I dont like it","4":"I dont want decentralized voting"}}

the answers 1:N relation we can declare like this:

avote-vote/v1/QKMLMEWCNL:j{"q":"QKMLMEWCNLDG5IB5JHMQQXJX6YYND66ALXTJIOXMVMQT3OYTKQ6A","a":{"1":100,"2":10,"3":0,"4":0}}

This has feature that one can search for all answers for any question, as well as all answers to specific question

**Comment by scholtz** [comment]
Btw, it would be great if the community could define the schema or some standard for its own protocols.. at one place.. @fabrice102  do you think this git is the place or should we just put here links to our message standards somewhere?

**Comment by ipaleka** [comment]
Another question @fabrice102: do you have any guidelines for the same data separated in multiple transactions?

a) 
algoCityTemp:j0{"city":"Singapore",...}
algoCityTemp:j1{..."temp":35}

b)
algoCityTemp:j{"id":"0", "city":"Singapore",...}
algoCityTemp:j{"id":"1", ..."temp":35}

...

**Comment by scholtz** [comment]
@fabrice102  .. since it seems you are on holiday now, i took liberty to create Algorand Message Standard in my own github

https://scholtz.github.io/AMS/AMS-0001/AMS-0001.html

is that ok with you?

**Comment by SudoWeezy** [comment]
[ARC-2](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0002.md) is now in status Last Call. It will be final in 1 month if no one has another request.
