### ISSUE TITLE
Discussion for ARC-0013 - Community Algorand Standards

### ISSUE THREAD

**Issue by scholtz** [algorandfoundation/ARCs#20]
Please review #19 

The aim of the standard is to centralize decentralized developers standards to the algorand foundation github, so that the community will prosper from interchanging information of their custom protocols on algorand network.

**Comment by SudoWeezy** [comment]
Pr closed.Please, refer to the [discussion](https://github.com/algorandfoundation/ARCs/issues/9) for [ARC-0](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0000.md)
