### ISSUE TITLE
Implement Versioning for ARC-4

### ISSUE THREAD

**Issue by SudoWeezy** [algorandfoundation/ARCs#202]
The ARC-4 proposal, available at [ARC-0004](https://arc.algorand.foundation/ARCs/arc-0004), requires a versioning system to manage changes and updates effectively. We propose implementing a versioning scheme for ARC-4, aligning with the standard conventions used in software development.

## Motivation:
A standardized system will facilitate tracking and updating ABI. It will also help understand which subsequent versions of the ARC remain backward compatible.

## Implementation Plan:
The starting point for ARC numbering: I suggest using ARC-4000 as the initial number, analogous to software versioning, where releases could be incremented.

> The format will be 4.00.0, where 00 is related to major changes (AVM updates) & 0 to minor changes.
ARC-4000 will be a copy-paste of ARC-4
ARC-4001 might be just the same with a new alias 
ARC-4010 might be related to an AVM Changes like boxes 

## Expected Outcomes:
- Improved adaptability and traceability of ARC-4 proposals.
- Clearer identification and referencing of the ABI version.

**Still open to suggestions**
Please feel free to give your thoughts on this.

**Comment by joe-p** [comment]
Is there a reasoning for needing the versioning on the actual ARC number rather than just having a version field in the JSON?

I feel like it's more simple to say something ABI 1.3 compliant vs ARC-4030 compliant.

**Comment by SudoWeezy** [comment]
If we say ABI 1.3, what is the ARC number associated? a random one?

**Comment by SudoWeezy** [comment]
https://github.com/algorandfoundation/ARCs/pull/210
