### ISSUE TITLE
Feedback Request: NFT Advanced Features

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#22]
There have been a number of questions about the right way to implement certain features with NFTs in Algorand.  Starting an issue here to gather ideas for what features might go into the spec(s).

Examples of advanced features might include things like Royalty payments or Collections.

I'd like for anyone working or thinking about these things to chime in with their use cases.

**Comment by barnjamin** [comment]
Creating a new issue for NFT Collections here: https://github.com/algorandfoundation/ARCs/issues/25

**Comment by barnjamin** [comment]
Creating new issue for NFT Royalties here: https://github.com/algorandfoundation/ARCs/issues/27

**Comment by simonbelingar** [comment]
I would like to propose an additional property to handle the 3d nfts. The animation_url field doesn't work for this particular use case as i can see this field being used to provide a video clip of the asset, for the platforms that don't "support" the 3d display. 

as there are a lot of different formats being used across teh 3d modeling stack (.fbx, .obj, .stl......) i propose a following solution. 

introduce a "model_url" to the json schema - model url should point to a .zip archive that includes the follwing folders

- Material (optiona - metadata for the native usecase)
- Models (mandatory -> mesh reprensetation in agreed upon formats e.g. .fbx, .obj)
- Textures (optional -> texture to be used on the .png, if any)

Each containing appropriate files... Thats a standard hierarchy to represent 3d models and most libraries will be able to parse the .zip archive and link/map textures properly.

Curious to hear your thoughts, but i think its pretty essential to think about the 3d model NFT's becoming more and more frequent in teh future. 

We for one are working on a project with 3d NFT's and are also in talks with up-and-coming marketplace about this exact topic/implementation.

**Comment by tureki** [comment]
@simonbelingar I'm also looking to create 3d NFT on the Algorand network in the future, unfortunately, there has no standard for the 3d NFT now. You probably can propose an idea with ARC Pull Request based on your experience? And curious how the ETH/Others chain defined the 3D NFT spec.

**Comment by simonbelingar** [comment]
> @simonbelingar I'm also looking to create 3d NFT on the Algorand network in the future, unfortunately, there has no standard for the 3d NFT now. You probably can propose an idea with ARC Pull Request based on your experience? And curious how the ETH/Others chain defined the 3D NFT spec.

hey, thanks for the suggestion, i'll go ahead and do that later today. We've learned quite a bit about the topic since the time of writing the above post, happy to share the vision/our approach and to discuss potential pitfalls/improvements.

on the side note: curious to hear about your project and your insight.

Cheers

**Comment by Vytek** [comment]
I am very interested in this topic especially for its use within Immersive Virtulal Worlds that I am creating. However, I believe it is necessary to create a new ARC dedicated to the particular needs of 3D MESHs. They are often thought of as a white blob in some format, but the innovative idea is to allow an optimized flow to be created for transfer across the network. What do you think about?

**Comment by barnjamin** [comment]
@Vytek I'm not sure I understand the requirement yet but Please file a new issue specific to that interest and we can discuss there?
