### ISSUE TITLE
Suggestions after xGov's proposals - period 1. Suggested guidelines on what should be included in a proposal.

### ISSUE THREAD

**Issue by SudoWeezy** [algorandfoundation/ARCs#231]
The issue is open to enhance the xGov process based on this well-written comment. https://github.com/algorandfoundation/ARCs/pull/151/#issuecomment-1657093279

Having gone through all the finalized proposals of period 1, I find there need to be more targeted guidelines on what should be included in a proposal.

My suggestions:
- Please include references to all claims made (about teams qualifications, previous projects you worked on, any referenced statistics, etc.). This will simplify the work for xGovs, easing the process of verification, and thus increasing the chance of getting the needed votes.
- When describing deliverables for the milestone for which you are requesting the funding in the proposal, please keep in mind that xGovs will need to be able to (easily) verify your deliverables to sign-off on the last payment. To mitigate potential conflicts, define in as much detail as possible what the deliverables will actually be. The more information you provide, the better. Some examples:
	- The milestone is to build a smart contract and an app, and get it to testnet. Describe how the interface will look like, e.g. CLI, basic UI or fully styled UI with multi-wallet connectivity (providing any mock-ups is another plus), and what interactions will the users be able to do and any limitations (e.g. initially pay only with ALGO for a service and not ASAs).
	- The milestone is to build a community. Provide metrics you would consider the milestone sufficiently fulfilled, e.g. have X followers on Twitter/Instagram/Youtube, Y members on Discord where phone number verification is required to prove that members are human, or have Z posts over N days on Reddit with accounts older than M days.
	- The milestone is to audit a smart contract. Write where the results of the audit will be published, by which companies it will be done, etc.
- It is beneficial to address and reference the existing competition for your product. What are their limitations and why are you better? If you are bringing an existing solution from another chain to Algorand, include how used those are. 
- What are your plans for long-term maintenance and sustainability of your product? Do you have a plan to monetize it or is it expected to become fully community driven?
- Who is the target user of your product and what's your general approach to reach them? E.g. if the product is a tool to ease creation of NFTs for creators, you have approached creators who would like to use it and spread it by word-of-mouth in the NFT community.
- When requesting larger amounts, please consider publicly doxxing. This should increase xGovs confidence in your good intentions due to increased accountability.
- Consider addressing how will the grant funds be spent. For example: X ALGO will be dedicated to covering transaction fees and opt-in costs for easier on boarding of new users, Y ALGO will be used to participate in consensus on a node run by the project to increase the reliability of your services by submitting your own transactions and blocks, Z ALGO will be sold on DEXs to pay for operational costs, N ALGO will be used as direct developer rewards vested over a period of half a year, M ALGO will be put in project treasury, K ALGO will be used for token buyback, L ALGO will be used as collateral for a loan, or anything else.
- If you have any video pitches or deck slides, include a link to them!
- Be pro-active in convincing xGovs to vote for your proposal. Engage on platforms like <a href="https://forum.algorand.org/">Algorand Forum</a>, <a href="https://discord.com/invite/algorand">Algorand Discord</a>, <a href="https://www.reddit.com/r/AlgorandOfficial/">official Algorand Reddit</a> or community-driven sub specifically for <a href="https://www.reddit.com/r/xGov/">xGovs</a>, and <a href="https://twitter.com">Twitter</a>, where many community-driven spaces discuss xGov proposals.

Providing these information will ease the work of xGovs and minimize amount of spam/low-quality proposals.
I think this is crucial because if e.g. an xGov spends just 2 min on a spam/low-quality proposal, at 4.8k xGovs, this amounts to one full month of man-hours wasted for the community for each spam proposal.
I think the current implied ethos of the xGov program should change from "projects submit proposals and xGovs need to figure out which are worth supporting" to "projects submit proposals and convince xGovs to support them".

_Originally posted by @ShaperOfEntropy in https://github.com/algorandfoundation/ARCs/issues/151#issuecomment-1657093279_

**Comment by 2lobo** [comment]
if the proposer needs a part of the requested amount upfront mention this in the proposal and argue why its necessary

**Comment by SudoWeezy** [comment]
Should this be part of the Header table as an option?

**Comment by ShaperOfEntropy** [comment]
I agree with @2lobo that if funds are needed upfront, it should be stated in the proposal and argued why it is necessary. This could simply be another part of the proposal guidelines and regardless of the amount requested. I do not see a need for this to be part of the header table (if it were, it would perhaps already clutter it too much).

Similarly, I would suggest that the proposers can also provide a list of third party entities that are willing to verify and sign-off on the delivery of the proposal (in which case the approval of the proposal by xGovs signals that xGovs agree with the delivery verification method and delegate their power to the suggested verifiers). Such a verification committee could consist of well-known community members, experts in the field, etc.

I would also suggest to add a hard requirement (i.e. not just a guideline) of a maximum abstract length (e.g. 250 words or 1500 characters).
