### ISSUE TITLE
ARC-2 MessagePack example does not follow specification

### ISSUE THREAD

**Issue by FerGT50** [algorandfoundation/ARCs#251]
According to
https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0002.md

ARC-2 with MessagePack data format needs 'm' after dapp-name:

But the given example (in Base 64), shortly after, which is
"YWxnb0NpdHlUZW1wL3YxOoKkY2l0ealTaW5nYXBvcmWkdGVtcBg="

does not contain the 'm'.

Should we follow the specification (with 'm' as data format specifier) or the example?

Thanks

**Comment by SudoWeezy** [comment]
You should follow the specification, if <data> is a MsgPack, <data-format> should be m
