### ISSUE TITLE
Discussion: Support of pre-ARC-3 tokens

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#31]
ARC-3 (https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0003.md, #3) proposes a new set of conventions to specify non-fungible and fungible tokens on the Algorand blockchain.

However, NFTs have been issued before ARC-3 and it is important that marketplaces, blockchain explorers, and wallets are still able to display those NFTs appropriately. Towards this goal, this issue is meant to lead to a list of ways NFTs have been represented in the past.

If you issued NFTs in the past, we enjoin you to provide below a description of how you represented NFTs and a way to recognize your NFTs.

The most common way seems to be the following:
* the URL points to the image/media asset

But is any metadata specified in any way for those NFTs?

Please respond below.

**Comment by mxmauro** [comment]
May be the asset owner can send a TX with a specific note with details of the asset id and the url + metadata. They also may send the TX to testnet to avoid costs.

**Comment by robert-zaremba** [comment]
How about the following:
* owner should create a JSON document in compliance with ARC3. Moreover to the required attributes, it should also include a `type`, which is either NFT, FT, or "other", and an `asset-id` attribute withe the ID of related asset.
* Algorand will create a special account `A` which will register special transactions defined in the next point.
* owner must create an empty transaction from the owner account to the account X with an URL.
* Indexers will monitor such transactions and validate  for each transaction, if asset-id referenced in the linked JSON document is indeed registered at owner account. The indexer will use that information to provide ARC3 Compliant information about the asset . This will be used by wallets and other tools.

**Comment by robert-zaremba** [comment]
Other idea is to create an on chain registry, where only the ASA owner can record an URL to ARC3 compatible metedata.

**Comment by SudoWeezy** [comment]
I have reached out to many "old" NFT projects. Most of them migrated to [ARC-69](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0069.md).
