### ISSUE TITLE
arc-0054

### ISSUE THREAD

**Issue by Bhaney44** [algorandfoundation/ARCs#312]
**Introduction**
I think [arc-0054](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0054.md) proposes one of the most useful technologies developed by Algorand by creating a network wide mechanism for verified burns. 

**Issues**

1. There appears to be no way to verify the private key security of the Burn Address.

The Burn Address`BNFIREKGRXEHCFOEQLTX3PU5SUCMRKDU7WHNBGZA4SXPW42OAHZBP7BPHY` was funded by`ZA5Y6ZVM2KOOV7JIIN3LSFNTCZDSOEHVFG6BECIFDIVFPIJWO7AVPO5OZI` with TXID `CY2OQBJFSB6N7C27FJ2KCONAEJGQAZYLIAWUST7RUWMLFGMLOYUA`. The funding address is still active for both receiving and sending assets. Moreover, the approval program makes no apparent mention of creating the Burn Address. Instead the approval program states:

```
	global CurrentApplicationAddress
	itxn_field AssetReceiver
```

So, one issue here is that it appears possible that there is an owner of the private key for the Burn Address or that the private key for the Burn Address is potentially recoverable. The other issue is that it appears possible to change `CurrentApplicationAddress`.

2. The Burn Address does not appear to be connected to an Application ID as specified in the approval program.

I searched the [Burn Address on PeraExplorer](https://explorer.perawallet.app/address/BNFIREKGRXEHCFOEQLTX3PU5SUCMRKDU7WHNBGZA4SXPW42OAHZBP7BPHY/) and found that it was not connected to any Application ID. The first lines of the approval program state:

```
txn ApplicationID
int 0
>
```

The issue here is there appears to be no way to verify that this approval program is connected to the Burn Address because the Burn Address has no associated applications.

**Comment by grzracz** [comment]
This user got his question answered multiple times on Discord and refuses to believe that an application address is created when an application is deployed & the unique "BNFIRE" address was a lot of engineering work from D13.

https://www.blockpack.app/#/explorer/application/1257620981/global-state

**Comment by tasosbit** [comment]
In short, the BNFIRE.. account is the application's natural escrow address, so there is no private key and never was

> The other issue is that it appears possible to change CurrentApplicationAddress.

This is a constant for each contract - the account address is derived from the application ID and so never changes for an application instance. For the bonfire one, the derived address just happens to be the BNFIRE.. one.

[More details here](https://forum.algorand.org/t/xgov-86-bonfire/10541/16)
