### ISSUE TITLE
Discussion: Suggestions regarding new forms of hierarchical/relational NFTs, natively

### ISSUE THREAD

**Issue by HashMapsData2Value** [algorandfoundation/ARCs#32]
Algorand is more and more establishing itself as the best platform for representing ownership of arbitrary things of value. With its low fees, instant finality, 0 forking, scalability, approach to storage (vault, compact-cert, RtbF), etc; it is taking tokenization to another level.

I'm very fascinated by these supply chain partnerships:

- [Italia Oliviacola](https://www.algorand.com/resources/ecosystem-announcements/italia-olivicola-leverages-algorand-to-improve-supply-chain-transparency-and-efficiency)
- [VeriTx](https://www.algorand.com/ecosystem/use-cases/veritx)
- [Carnes Validades](https://algorand.foundation/news/carnes-validadas-grant-award)
- [Authentium](https://authentium.io/)
- [Blockchain Plaza](https://www.blockchainplaza.it/it-it/home)
- [Liquid Vineyards](https://www.liquidvineyards.com/)

Consider the following scenario:

You have a tea farm. On that farm, you own a [1000 year old tea tree](https://en.wikipedia.org/wiki/Da_Hong_Pao) whose tea is super expensive. Every time you harvest it, you create an NFT representing a specific batch of tea.  In fact, maybe you have tokenized the tree and so there are other stakeholders that get a share of the profit from the tree.

You sell these off to the next layer in the supply chain - a packaging firm. The packaging firm has eco-grade containers that is good for the environment. They mate the tea leaf batch NFT + 30 empty containers -> 30 containers of excellent tea, child tokens. As part of this mating, the parent tokens are destroyed. But there is still a reference to them in the child tokens.

The containers are shipped to my local fancy tea shop. I show up and buy a container of fine tea in an atomic transaction, X Algo for the tea. 

I come home, curious to see where the tea came from. Well, using your token, you should be able to find the parent tokens, and in turn be able to see that your tea did in fact come from the your tea farm, as well as the eco-grade packaging (might have been recycled plastic, its own parent-child relationship).

This can extend to other cases as well. For example, consider a dairy cow NFT that is "harvested" for milk tokens/milk batch NFTs.  It is consuming water (scarce resource in some places), feed and medicine, so we have a partial-group destruction (cow lives, other assets are consumed in the mating). One day the cow will be "economically nonviable" and slaughtered (single parent being destroyed) resulting in child tokens being created representing the cow's organs and muscles, that in turn get sold. Maybe the origin of the feed itself is sensitive, maybe the end-customer wants to be sure it's not soy feed coming from the Amazon Rainforest land that was burnt down.

So as you can see, in supply chains you have chains and cycles of products that go into other products. There are **Harvestable Tokens**, tokens able to produce new NFTs*. Tokens can be **mated**, that is, create new tokens into existence at the cost of one themselves (group destruct transaction). And there is always this hierarchical/relational structure to things, you might call it a parents-children/many-to-many relationship.

I believe embedding these types of hierarchical/relational/temporal activities natively in the Algorand blockchain would be very helpful, especially in lowering the barrier-of-entry for developers.

I'd like to hear people's thoughts. I'm sure there are some storage concerns that come with inserting the extra information necessary to make it happen into the tokens themselves.

\* If it was just producing FTs it would be easy to implement actually. Just mint the FTs and hold them in reserve. Assign the reserve address to a smart contract. Create a governance token for that smart contract, i.e. the Harvestable token. I believe that it might require more work to mint a new NFT, with new addresses and hash values and so on.

**Comment by HashMapsData2Value** [comment]
So thinking it over, would be nice to be able to:
- set a parent-pointer. However, not anyone can make a parent-pointer pointing just anywhere.
- run a group deletion+minting transaction that takes in arbitrary input tokens and destroys them while simultaneously creating arbitrary output tokens. We call this group transaction a **Transmutatation**.

The parent-pointer can:
- point from one NFT to a parent NFT, but ONLY if it was "**harvested**" from that NFT.
- point from one NFT to a parent transmutation event.

So introduce:
- A parent/pointer address.
- A harvest address for each NFT. The harvest address has the privilege to harvest new tokens whose parent addresses are set to the token.
- The transmutation group transaction, which takes in an arbitrarily sized input of tokens that are destroyed in favor of new tokens whose parent address -> the transmutation ID\*

Lifecycle of dairy cow:
- Is continuously "harvested" for milk tokens by the harvester address, producing milk tokens with parent pointers to the cow.
- Is finally "transmuted" into a group of meat/organ tokens\*, which have their parent address pointing to the transmutation tx id.


\* Question: How will this interfere with the right to delete tokens? Should we connect it to the the harvest address, so that only the harvest address is allowed to harvest (create a new token pointing to this token) AND is allowed to transmute it (which would destroy the token). 

You could have a smart contract as the harvest address, and it will only approve transmutations IF the right group of tokens are involved as input and are created as an ouput.

**Comment by SudoWeezy** [comment]
If the case is still relevant, please open a topic on the [forum](https://forum.algorand.org/c/arc/19)
