### ISSUE TITLE
Discussion: Dynamic NFTs

### ISSUE THREAD

**Issue by tejas-kothari** [algorandfoundation/ARCs#37]
NFTs have been all the craze and hype in 2021. However, they have remained relatively low-tech because they are essentially tokens linked to a URL containing static images. In other words, when you purchase an NFT, the artwork remains unchanged throughout its life.

That's why we have the idea to create dynamic NFTs, which can connect to off-chain data through oracles and "react" accordingly. For example, the NFT image would show a rocket going up when crypto prices are up and down when prices are down.

I also believe the technical implementation shouldn't be too difficult on Algorand. Each individual image of a dynamic NFT would be stored on IPFS. The NFT's on-chain metadata would hold these IPFS links. When a user requests the image URL, the NFT smart contract would request data from the oracles (crypto prices for the above example), select the correct URL accordingly, then return it to the user.

I would love to hear people's feedback regarding this idea and its technical implementation.

**Comment by wheresaddie** [comment]
yes I would absolutely love to see this @tejas-kothari - some of the only generative and parametric works Ive seen have been on eth ( https://www.artblocks.io/ ) -- with the upcoming bridges rolling out to support eth < > algo, I would be curious to know if we could leverage some support of these file types in our own arcs for NFTs as it would draw a huge market and artist group from the current limited options on eth.  I am specifically interested in webGL, html, p5 etc. cc @fabrice102

**Comment by pbennett** [comment]
Once an ABI is in place for contract-based NFTs that wallets/etc support, then I would think this would be a simple matter of returning a different URL from the URL method (like ERC721).

If you're asking about this for existing ASAs, I have a plan for this actually, and plan to create an ARC for it soon.  If you have IPFS data then you will simply be able to pass in a new hash to your contract to update an ASA it has configuration rights over.  It will only require trivial changes for NFT clients rendering NFT ASAs, and will support huge metadata references.

**Comment by SudoWeezy** [comment]
Solved in https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0019.md
