### ISSUE TITLE
Discussion for ARC-0014 - Algorand Standard for authentication

### ISSUE THREAD

**Issue by scholtz** [algorandfoundation/ARCs#42]
Please comment on https://github.com/algorandfoundation/ARCs/pull/41/files  - Algorand Standard for authentication

#41

At the Swiss Blockchain Hackathon as a side product we have developed the authentication mechanism for authentication of algorand accounts.

Person just have to sign the zero transaction, and use it the similar way as JWT tokens are being used. The backend has this way the information that the account which calls the methods is capable of signing the messages. It does not cost anything because the transaction must not go to the network, but can be validated by the backend service as valid signed transaction. Expiration of this token is handled by the suggested params in the transactions - the latest block parameter.

.net implemetation: https://github.com/scholtz/AlgorandAuthenticationDotNet

**Comment by scholtz** [comment]
GraphQL authentication webhook for ARC0014 https://github.com/scholtz/HasuraAlgorandAuthWebHook

https://hub.docker.com/r/scholtz2/hasura-algorand-auth-web-hook

**Comment by scholtz** [comment]
There has been another implementation using Algorand .net auth

https://github.com/scholtz/AlgorandKMDServer

Open api specs: http://kmd.h3.a-wallet.net/swagger/

Implemented in AWallet .. https://github.com/scholtz/wallet

Video on how to make account online with arc0014 auth: https://www.youtube.com/watch?v=cSJjmnzvvLY

**Comment by scholtz** [comment]
For the record the activity diagram of the original ARC-0014

@startuml

User -> Website: User wish to login to the website 


Website -> AnyAlgorandNode : Request /v2/transactions/params
AnyAlgorandNode  -> Website : Returns transaction params

Website -> Wallet : Website produces through algosdk messege to be signed, note as realm, params as session timeout
Wallet -> Website: Signed tx, website stores tx in temporary memory, localstorage or cookie the same as jwt

Website --> User: Displays eg auth address

Website -> Backend: Request authorized method, use SigTx Authorization header, fe /getUser

Backend -> AnyAlgorandNode : Request /v2/transactions/params
AnyAlgorandNode  -> Backend : Returns current block round number

Backend -> Website: 401 if signature, genesis or round is wrong
Backend -> Website: 200 if authorized and returns content

Website --> User: Displays /getUser content, fe roles or username

@enduml

![image](https://user-images.githubusercontent.com/1223439/195995662-5d93f547-ff4a-4277-8546-74a627194dc8.png)

**Comment by Miamoto-Musashi** [comment]
how does this relate to wallet connect?

**Comment by scholtz** [comment]
i have noticed that transaction type of authentication is being used in many projects now, should we push forward with this arc?

**Comment by pbennett** [comment]
There's this now as well though: https://github.com/algorandfoundation/ARCs/pull/160
ARC-0031
