### ISSUE TITLE
Creating Fungible Asset Scarcity

### ISSUE THREAD

**Issue by ObiajuluM** [algorandfoundation/ARCs#43]
I already opened this issue in Algorand's default repo
Please read it [here](https://github.com/algorand/go-algorand/issues/3197).

Thanks.

**Comment by wheresaddie** [comment]
hey @ObiajuluM -

thanks for your contribution and inputs. this is a great approach to how we can consider fungible asset scarcity. one major roadblock is that Algorand will not fork so afaik the only viable approach here would be to consider updating to add a new global address.
