### ISSUE TITLE
Copyright Waiver

### ISSUE THREAD

**Issue by Bhaney44** [algorandfoundation/ARCs#45]
I was hoping to get some more information about the open source strategy at the Algorand Foundation. I think the open source software strategy is allowing us to drive the edge in innovation right now. The global nature of software development on Algorand is incredible and it wouldn't be possible without open source code. What was the basis for the decision to use the [Creative Commons Copyright Waiver](https://creativecommons.org/publicdomain/zero/1.0/), rather than the [MIT License](https://opensource.org/licenses/MIT), with the copyright assigned to the Algorand Foundation for the ARCs? What is the protocol for how the Foundation makes code open source and determines how to make software open source? Thanks in advance!

**Comment by wheresaddie** [comment]
hey @Bhaney44 - Generally speaking we always look for truly decentralised projects to support an open source ecosystem. As a layer 1 protocol/Algorand- anything licensed to us, may be sub-licensed under the relevant licensing. The actual oss license used by devs obviously sometimes varies on a case by case basis-  I tend to recommend considering the Affero General Public License v.3 (“AGPL v3”) and any changes to Algorand should in theory also be open sourced under an AGPL v3 contributor license. Overall, I tend to see most projects such as indexes, bridges,AMMs, APIs, and SDKs etc  licensed by or under the MIT or AGPLv3 License with some exceptions..

**Comment by Bhaney44** [comment]
Thank you @wheresaddie!
