### ISSUE TITLE
Attribute specification on ARC3 NFTs

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#47]
To support things like attributes on ARC3 NFTs, we should define a standard for describing them.  It may be as simple as an additional field in  the `properties` section that is an array of objects describing the attributes

```json
{
  "...":"...",
  "properties":{
    "...":""
    "attributes":[
      {"trait_type":"Background", "value":"Yellow"}, 
      {"trait_type":"Shirt", "value":"Algorand" },
      {"trait_type":"Eyeballs", "display_type":"number", "value":3}
    ]
  }
}
```

The opensea specification for attributes may be a good one to mirror
https://docs.opensea.io/docs/metadata-standards#attributes

Please comment with anything I'm missing or alternative suggestions

**Comment by fergalwalsh** [comment]
I think there is definitely a value and need for this. It's something I have been thinking about recently. 

The rest of my comment is meta:
I support the idea of defining this as a 'subspec' of ARC3 - i.e. ARC3 as the container and a new spec that gives semantics to specific fields of `properties`. 

Allowing for a metadata document to adhere to multiple specs within the same container seems desirable. Including properties such as `"arc41": true, "arc82": true` would allow for this, assuming these two particular standards deal with different things (traits & royalties for example) and don't contradict each other on the semantics of particular properties.

Or alternatively like this:
```
{
   "...": "",
    "properties": {
       "...": "",
        "arc41": {
            "attributes" : [
                {"trait_type":"Background", "value":"Yellow"}, 
                {"trait_type":"Shirt", "value":"Algorand" },
                {"trait_type":"Eyeballs", "display_type":"number", "value":3}
            ]
        },
        "arc82": {
            "royalties": {
                "percentage": 5,
                "beneficiary": "..."
            }
        }
    }
}
```

**Comment by barnjamin** [comment]
Great point about name spacing these

**Comment by whereisrysmind** [comment]
I really like the name-spacing suggestion, i may go ahead and start doing it this way. It enables using different MD standards natively within arc3.

**Comment by wheresaddie** [comment]
120% support this, I also support the name spacing and define `properties` array for objects describing collections attributes will be key in further secondary market plays.

What are the thoughts on `numeric trait`- do we want to consider setting a ceiling for possible values or define defaults to the max per contract?

**Comment by barnjamin** [comment]
>What are the thoughts on numeric trait- do we want to consider setting a ceiling for possible values or define defaults to the max per contract?

Maybe max safe int in JS? I think its 2^53-1.  larger than that and we should have it specified as a numeric string that can be parsed into some valid N byte value

**Comment by koen-vr** [comment]
> Allowing for a metadata document to adhere to multiple specs within the same container seems desirable. Including properties such as `"arc41": true, "arc82": true` would allow for this, assuming these two particular standards deal with different things (traits & royalties for example) and don't contradict each other on the semantics of particular properties.
> 
> Or alternatively like this:
> 
> ```
> {
>    "...": "",
>     "properties": {
>        "...": "",
>         "arc41": {
>             "attributes" : [
>                 {"trait_type":"Background", "value":"Yellow"}, 
>                 {"trait_type":"Shirt", "value":"Algorand" },
>                 {"trait_type":"Eyeballs", "display_type":"number", "value":3}
>             ]
>         },
>         "arc82": {
>             "royalties": {
>                 "percentage": 5,
>                 "beneficiary": "..."
>             }
>         }
>     }
> }
> ```

I'm not sold on the namespacing, what if two arcs have overlapping behaviors/values? That said I like the idea of having arcs as 'subspecs' in some way or form and adding a way to opt-in on them.

**Comment by MrJackdaw** [comment]
> I'm not sold on the namespacing, What to do if two arcs have overlapping behaviors/values, duplicate them? That said I like the idea of having arcs as 'subspecs' in some way or form and adding a way to opt-in on them.

This is a valid concern, and raises a question: does `ARC3` (as a container) define rules for its child ARCs, or does it just remain a loose "NFT Attribute container" and leave sub-spec decisions to their creators?

**Comment by keeganthomp** [comment]
After thinking about this more, I think nesting standards or treating ARC3 as a container is going to get messy.

ARC69 deprecated attributes in place of properties as of 10 days ago (https://github.com/algokittens/arc69/pull/16). So keep that in mind before reading further.

I believe ARC3 `properties` was made to be flexible. I do not think there is a need to nest meta data standards.

I know the community has rallied behind ARC69 `trait_type` and `value` paradigm, but I think now is the time to define a lasting standard that makes the most human readable and code digestible format. I believe that to be an object/ properties as it requires let storage than having `trait_type` and `value` for every single attribute. get's expensive.

Let me explain:

The token (ASA) can always have name , unitName and description (if desired). The top level of ARC3 also has optional name and description. Therefore, there is no need to duplicate these in the meta data/ properties. properties should be seen as attributes where the key is the "trait type" and the value is said trait type's value.

if there is a new ARC proposed in the future, one would just need to make sure their NFT/ASA follows that standard or has the desired properties of that new ARC.

For example, if future ARC82 dictates that "deed NFT's" need a city, state, and zip, then you just simply add city, state, and zip to properties object:

I.e.
```
{
   "name":"Deed for 505 Yellowbrick Rd",
   "description":"505 Yellowbrick Rd Deed",
   "properties":{
      "city": "Oz",
      "state": "Montana",
      "zip": 12345
   }
}
```

To accommodate rarity or "traits", I propose this:

_ARC3 properties attribute, which is made up of Arbitrary properties (also called attributes). Values may be strings, numbers, object or arrays, has a reserved key "traits" that is optional. If "traits" is provided to properties, it must be an object whose values may be strings or numbers. "traits" is a common property for PFP's and other NFT's that need to calculate rarity_

**Comment by fabrice102** [comment]
I also think the namespacing may become cumbersome quite quickly and may indeed require duplication as mentioned by @koen-vr .
I think having properties implementing multiple ARC is akin to a class implementing multiple interfaces in Java for example.

I think everybody on this issue saw https://github.com/algorandfoundation/ARCs/pull/61, but just highlighting that this very related PR.

**Comment by fabrice102** [comment]
> ARC69 deprecated attributes in place of properties as of 10 days ago ([algokittens/arc69#16](https://github.com/algokittens/arc69/pull/16)). So keep that in mind before reading further.

There is a little issue there because ARC69 only accept "simple_property" that are just a single string, as opposed to `traits` that is an object.

**Comment by keeganthomp** [comment]
It's an object, but the keys in said object would need to be "simple" according to this spec as well. That is, each value of the traits object must be a string or number.

**Comment by barnjamin** [comment]
This is solved in ARC16
