### ISSUE TITLE
Discussion for ARCs 0005 to 0011: Wallet for dApps standard

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#52]
This issue is to discuss the standardization effort of wallets for dApps, initially proposed by Reach in #8 and merged as draft in the main repo as part of #51.

For details about the changes since Reach proposal, see #51.

The goal of these ARCs is to allow all dApps to use all the available wallets using a single interface.
This would allow to significantly lower the difficulty to support many wallets.

Wallets that are not available as extensions such as WalletConnect and MyAlgoConnect are expected to propose a small shim that would make them compatible with this ARC.

Some questions to be discussed:
* should we consider splitting the error standards out of ARC-0001 and make it a living standard
* should we allow optional argument to post without waiting for confirmation (this may not be recommended as nothing ensures that transactions are properly sent in that case).

Rational citing ARC 0010:
> In order for a wallet to be useable by a DApp, it must support features for account discovery, signing and posting transactions, and querying the network.
>
> To whatever extent possible, the end users of a DApp should be empowered to select their own wallet, accounts, and network to be used with the DApp. 
> Furthermore, said users should be able to use their preferred network node connection, without exposing their connection details and secrets (such as endpoint URLs and API tokens) to the DApp.
> 
> The APIs presented in this document and related documents are sufficient to cover the needed functionality, while protecting user choice and remaining compatible with best security practices.
> Most DApps indeed always need to post transactions immediately after signing.
> `signAndPostTxns` allows this goal without revealing the signed transactions to the DApp, which prevents surprises to the user: there is no risk the DApp keeps in memory the transactions and post it later without the user knowing it (either to achieve a malicious goal such as forcing double spending, or just because the DApp has a bug).
> However, there are cases where `signTxns` and `postTxns` need to be used: for example when multiple users need to coordinate to sign an atomic transfer.

**Comment by barnjamin** [comment]
Overall I like all the specifications and I like how they're structured.  Below are some nits and questions.

Please also help me understand arc-0009 and how arc-0011 will work in practice.

```md

#ARC-0005

s/signTxn/signTxns

describe what opts might be

describe when null is returned

#ARC-0006

string spec for address, link directly to line

reword:
`acknowledge control` to `approve access` and maybe futher `for the requesting dapp`


reword:
where `ret.accounts` is an array that *starts* with all the same elements as `opts.accounts`, in the same order.
where `ret.accounts` is an array that *contains* with all the same elements as `opts.accounts`, in the same order.

I think we remove this:
`The wallet MAY allow the user to provide more accounts than those listed.`
If the requestor specified accounts, those are the only ones that should be allowed. Allowing the requestor to omit specification of account list provides custom account specification by the wallet user


#ARC-0007

Why not include _all_ the transaction ids? There is no mention that they _must_ be atomically grouped, so a singled txid may not be sufficient


#ARC-0008

Link directly to the specification in in markdown files for WalletTransaction/PostTxnsResult


#ARC-0009

I don't quite understand this one, Is the Dapp getting an active connection to a custom algod/indexer? Can it run whatever requests it wants?


#ARC-0010

Link directly to specification section in markdown files

Unless I misunderstand ARC9, This seems to mix prescriptions for a $dapp into the wallet spec:

`
The result of `getAlgodv2` SHOULD only be used to query the network. `signAndPostTxns` SHOULD be used to send transactions to the network. The `Algodv2` object MAY be modified to throw exceptions if the caller tries to use it to post transactions.
`

#ARC-0011

How does window.algorand get set? Some standard for wallet selector?
```

**Comment by DanBurton** [comment]
I am preparing some responses to @barnjamin 's very helpful comments.

But I wanted to quickly add my response to one of the questions posed by @fabrice102 :

> should we allow optional argument to post without waiting for confirmation (this may not be recommended as nothing ensures that transactions are properly sent in that case).

I find this unnecessary. The dapp developer can simply choose to ignore the promise -- meaning: _not_ `await` it -- if that is what they want to do.

**Comment by DanBurton** [comment]
In response to @barnjamin, I am creating a PR to the ARC with some updates. Here are my responses: 

```
#ARC-0005

s/signTxn/signTxns
* Dan: will do

describe what opts might be
* Dan: will do

describe when null is returned
* Dan: will do


#ARC-0006

string spec for address, link directly to line
* Dan: will update to section link (line links are brittle)

reword:
`acknowledge control` to `approve access` and maybe futher `for the requesting dapp`
* Dan: Mixed feelings. I like the original wording because "approve access" specifies more than I intended.
  Wallets may choose whether or not to "approve access" to accounts
  even if they have not been acknowledged in this manner.

reword:
where `ret.accounts` is an array that *starts* with all the same elements as `opts.accounts`, in the same order.
where `ret.accounts` is an array that *contains* with all the same elements as `opts.accounts`, in the same order.
* Dan: I need to contemplate this. Again, our goal was to specify only the minimum amount necessary.
  But allowing additional accounts to be returned seems unnecessary, so , this change is worth considering.

I think we remove this:
`The wallet MAY allow the user to provide more accounts than those listed.`
If the requestor specified accounts, those are the only ones that should be allowed. Allowing the requestor to omit specification of account list provides custom account specification by the wallet user
* Dan: our (Reach's) goal is to impose the minimum requirements necessary for a wallet to function;
  I will rephrase "MAY" to "MAY, but SHOULD NOT" to communicate the spirit of this without mandating it.


#ARC-0007

Why not include _all_ the transaction ids? There is no mention that they _must_ be atomically grouped, so a singled txid may not be sufficient
* Dan: The reason the spec said only 1 was because this matches the JavaScript algosdk library and the JSON API call.
  sendRawTransaction(bs) --> POST /v2/transactions
  https://developer.algorand.org/docs/rest-apis/algod/v2/#post-v2transactions
  However, it  should be fairly simple for wallets to return all txn IDs.
  And perhaps there should be accompanying changes to the API endpoint and algosdk library.
  So this is also a change worth considering.


#ARC-0008

Link directly to the specification in in markdown files for WalletTransaction/PostTxnsResult
* Dan: will link to section (line links are brittle)


#ARC-0009

I don't quite understand this one, Is the Dapp getting an active connection to a custom algod/indexer? Can it run whatever requests it wants?
* Dan: Yes. But the wallet may provide a restricted client where
  certain queries are refused client-side before they even go out over the connection.


#ARC-0010

Link directly to specification section in markdown files
* Dan: will do

Unless I misunderstand ARC9, This seems to mix prescriptions for a $dapp into the wallet spec:

`
The result of `getAlgodv2` SHOULD only be used to query the network. `signAndPostTxns` SHOULD be used to send transactions to the network. The `Algodv2` object MAY be modified to throw exceptions if the caller tries to use it to post transactions.
`

* Dan: I agree and I will reword this section to de-emphasize how the API should be used,
  and instead indicate the same idea simply by describing
  what kinds of restrictions the wallet MAY impose upon dapps, and why.


#ARC-0011

How does window.algorand get set? Some standard for wallet selector?
* Dan: That's up to each wallet to figure out.
  "Wallet selector" could itself be a "wallet" that dispatches to other wallets.
  A well-behaved dapp should respect whatever it finds at `window.algorand`,
  rather than creating its own UI for wallet selection.
  This places wallet selection in the user's hands, not the dapp's.

```

**Comment by barnjamin** [comment]
>* Dan: Mixed feelings. I like the original wording because "approve access" specifies more than I intended.
  Wallets may choose whether or not to "approve access" to accounts
  even if they have not been acknowledged in this manner.

That makes sense, the suggestion was to not imply that the app has some authority over your account, meaning you'd still be able to decline transactions.

>* Dan: Yes. But the wallet may provide a restricted client where
  certain queries are refused client-side before they even go out over the connection.

makes sense, thanks for the detail

>* Dan: That's up to each wallet to figure out.

Maybe we need to mention or prescribe that the wallet should be setting this state?

**Comment by fabrice102** [comment]
Regarding `window.algorand`, it's easy to set for browser extension.
However WalletConnect and MyAlgoConnect cannot really set `window.algorand`.
So I think a UI selector is still required. The UI selector may be bypassed when an extension set `window.algorand`.
I guess we could also consider having a browser extension that acts as a UI selector itself.

But first and foremost, I think it would be great to have at least one UI selector that is easy to integrate. The UI selector would only pop-up if window.algorand is not specified. What do you think?

**Comment by jeapostrophe** [comment]
Re: WalletConnect and MyAlgoConnect --- In my opinion, this means that they cannot implement the ARC11 spec, by choice and design. However, someone could make an ARC11 wallet that used them internally and only provided the browser extension shim. This would be a very minimal and simpler to write ARC11 wallet. (At Reach, we've already made the adapter part that takes the interfaces WC and MAC provide and provide the ARC11 functions, we just haven't made the browser extension part.)

**Comment by kewde** [comment]
1. The ARC11 spec should not make any recommendation towards where to inject to. Users may have multiple extensions installed, a single `window.algorand` object is not enough. We'd recommend not making any suggestion about where to inject into, or provide a way for extensions to register into a common registry.
2. In our opinion, the browser extensions shouldn't be responsible for exposing an algod client and indexer because these servers have feature-toggles which may or may not be enabled resulting in inconsistencies between extensions.
```
  getAlgodv2Client: GetAlgodv2ClientFunction;
  getIndexerClient: GetIndexerClientFunction;
```

**Comment by olistic** [comment]
Exodus is also collaborating with the Solana Labs and other wallets on a multi-chain wallet standard (read more about it [here](https://github.com/wallet-standard/wallet-standard/tree/9f9b0b4a1577e799e113f3c7d4cc834fef5a8c66/packages/core/standard)). It would be amazing if the Algorand Foundation joined us on these efforts.
