### ISSUE TITLE
Non-ideal domain separation in ARC-0003 for extra metadata

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#54]
The asset metadata hash in ARC-0003 with extra metadata is currently computed as:
```
am = SHA-512/256("arc0003/am" || SHA-512/256("arc0003/amj" || content of JSON Metadata file) || e)
```
This is not ideal because `arc0003/am` is a prefix of `arc0003/amj`, hence it does not do a proper domain separation.

I see 3 solutions to fix it:
1. Leave it as is. The security risks are quite limited.
2. Modify the ARC as it is unlikely that people used this advanced feature. In that case, use `arc0003/ame` instead of `arc0003/am`.
3. Modify the ARC / create a new ARC in a backward compatible way by having the metadata JSON file indicate whether the old format or the new format should be used.

What are your thoughts?

**Comment by barnjamin** [comment]
Definitely add a comment, but I do think the security risk is limited enough that it doesn't need to be taken out of final state and no new ARC need be defined.

**Comment by wheresaddie** [comment]
+1 @barnjamin - if the sec issues are minimal - a comment should be sufficient
