### ISSUE TITLE
New ARC for using NFT and FT ASA 3D Mesh for 2D/3D format and streaming

### ISSUE THREAD

**Issue by Vytek** [algorandfoundation/ARCs#81]
I think that ARC 3 is not suitable for the needs of 3d meshes. Arc69 is better.
These are my concerns:

1) It is prefer to insert this json info in Note record not in a public json file associated with the blob. Note it is on BlockChain and it is signed and secure.
2) Image and other url is not useful. If I have the URL blob can I show it directely
3) We also think about streaming objects with different LOD and other system (I am searching the relate infos)  to transfer 3D mesh with or withoud compression
4) We add the MIME Type like ARC69 (I think is it better..) to define the different format correcatly like FBX, GLB, USD with or without compression 
5) Whe add to insert a correct HASH to check blob for fast check in BC transaction

I'll detail more by adding other specific reasons for creating a new ARC. All this also in anticipation of a possible future use of this standard in the creation of a true Open Metaverse.

**Comment by pbennett** [comment]
I suggest looking at arc19.  Provides for large metadata with multiple image links, all immutable, and the metadata and image links can all be changed out with a single 32-byte change, also not requiring the use of indexer searches.  All of the data is always available from any regular node (even non-archival)
https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0019.md

**Comment by Vytek** [comment]
For compression we don't have to keep systems like draco as a reference point but also completely different approaches such as the short system: http://vcg.isti.cnr.it/corto/index.html#overview

**Comment by Vytek** [comment]
Rereading Arc69 it seems to me that it is possible to use it with some modifications and to specialize it also for the needs of 3D / 2D Meshes. I do not close the issue yet as the discussion with other experts is still alive.

**Comment by Vytek** [comment]
See: https://github.com/algorandfoundation/ARCs/pull/87

**Comment by Vytek** [comment]
I modify all creating new ARC27: https://github.com/algorandfoundation/ARCs/pull/102

**Comment by SudoWeezy** [comment]
I will close this as the thread is now on the [forum](https://forum.algorand.org/t/draft-arc-27-for-3d-media-token-nft-and-ft/7707)
