### ISSUE TITLE
Web3 Metaverse Compatibility

### ISSUE THREAD

**Issue by maexx393** [algorandfoundation/ARCs#85]
This new issue is meant to discuss a new Algorand NFT standard for web3. As new technologies for the metaverse emerge we believe Algorand can take advantage of standards such as GLTF2 for 3D NFTs etc. I will be posting more information regarding the proposal

**Comment by barnjamin** [comment]
hey @maexx393 see https://github.com/algorandfoundation/ARCs/issues/81 also

**Comment by Vytek** [comment]
@maexx393 See: https://github.com/algorandfoundation/ARCs/pull/87

**Comment by SudoWeezy** [comment]
Topic already discussed elsewhere
