### ISSUE TITLE
Discussion for ARC-0000 :  ARC Purpose and Guidelines

### ISSUE THREAD

**Issue by fergalwalsh** [algorandfoundation/ARCs#9]
It would be great to have a document outlining the procedure for these ARCs. i.e. how they should be numbered, structured, decided upon, etc. Will rejected/abandoned ARC numbers be reused. Are the numbers required to be numbered N+1 or can a vanity number be chosen. Should a wide informal discussion take place somewhere before a formal ARC proposal? Or are these considered simply as documents and not necessarily standards of any kind?
These sorts of issues.

Perhaps the number 0 could be used for the ARC that retroactively defines the process?
If not an ARC, perhaps the repo README would be sufficient to define the process and expected structure?

I'd like to write an ARC for a specification so it would be useful to know the process. It would be self referential (like ARC3) so it would help to know the expectations for numbering.

Examples of initial proposals describing proposal processes:
https://www.python.org/dev/peps/pep-0001/
https://eips.ethereum.org/EIPS/eip-1

**Comment by emg110** [comment]
May I suggest (for contents of ARC0) a simple diagram which determines and illustrates roles of `ARC`, `ARC PR` & `ARC ISSUE` and a **simple bulleted instruction** on how to contribute and on which `ground rules` basis.

**Comment by fabrice102** [comment]
We should work on that.

In the meantime, let's keep things very simple. If you want to make an ARC:
1. Get support from the community on Discord/forum.algorand.org
2. Make a PR with a name: "New ARC: ARC-xxxx: title", where `xxxx` is replaced by the next available number. The PR should contain a single file `ARCs/arc-xxxx.md` which is formatted according to https://eips.ethereum.org/EIPS/eip-1 except for the header that should follow what is done in ARC-0001.

Discussion will happen on the PR which is simpler than on a separate issue (this is something we realized too late after making those issues).

We strongly encourage following the conventions:
> The key words "**MUST**", "**MUST NOT**", "**REQUIRED**", "**SHALL**", "**SHALL NOT**", "**SHOULD**", "**SHOULD NOT**", "**RECOMMENDED**", "**MAY**", and "**OPTIONAL**" in this document are to be interpreted as described in [RFC-2119](https://www.ietf.org/rfc/rfc2119.txt).

**Comment by fergalwalsh** [comment]
Thanks for the info @fabrice102 👍

**Comment by SudoWeezy** [comment]
[ARC-0](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0000.md) is now in status `Living`

Feel free to comment if needed.
